version: '3.1'

services:
  m1:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/m1/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - $PWD/initdb:/docker-entrypoint-initdb.d
    hostname: m1
    networks:
      - mysql

  m2:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/m2/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - $PWD/initdb:/docker-entrypoint-initdb.d
    hostname: m2
    networks:
      - mysql

  ha:
    image: haproxy:1.8.14
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    hostname: ha
    networks:
      - mysql
    ports:
      - 3306:3306
      - 80:80

networks:
  mysql:
