version: '3.1'

services:
  m1:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/m1/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - $PWD/initdb:/docker-entrypoint-initdb.d
    hostname: m1

  m2:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - /etc/localtime:/etc/localtime:ro
#      - $PWD/m2:/etc/mysql
      - $PWD/m2/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - $PWD/initdb:/docker-entrypoint-initdb.d
    hostname: m2

